package com.eslirodrigues.valorantmatches.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFBC112C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onPrimaryContainer = Color(0xFF410007)
val md_theme_light_secondary = Color(0xFF006874)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF97F0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F24)
val md_theme_light_tertiary = Color(0xFF745A2F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEAC)
val md_theme_light_onTertiaryContainer = Color(0xFF281900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDC)
val md_theme_light_onSurfaceVariant = Color(0xFF524342)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEED)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB3B1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFBC112C)
val md_theme_light_surfaceTintColor = Color(0xFFBC112C)

val md_theme_dark_primary = md_theme_light_primary
//    Color(0xFFFFB3B1)
val md_theme_dark_onPrimary =
    md_theme_light_onPrimary
//    Color(0xFF680012)
val md_theme_dark_primaryContainer = Color(0xFF92001D)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_secondary = Color(0xFF4FD8EB)
val md_theme_dark_onSecondary = Color(0xFF00363D)
val md_theme_dark_secondaryContainer = Color(0xFF004F58)
val md_theme_dark_onSecondaryContainer = Color(0xFF97F0FF)
val md_theme_dark_tertiary = Color(0xFFE4C18D)
val md_theme_dark_onTertiary = Color(0xFF412D05)
val md_theme_dark_tertiaryContainer = Color(0xFF5A4319)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEAC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1A)
val md_theme_dark_onBackground = Color(0xFFEDE0DF)
val md_theme_dark_surface = Color(0xFF201A1A)
val md_theme_dark_onSurface = Color(0xFFEDE0DF)
val md_theme_dark_surfaceVariant = Color(0xFF524342)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C0)
val md_theme_dark_outline = Color(0xFFA08C8B)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DF)
val md_theme_dark_inversePrimary = Color(0xFFBC112C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B1)
val md_theme_dark_surfaceTintColor = Color(0xFFFFB3B1)


val seed = Color(0xFFBE132D)
val color = Color(0xFFFA4454)
val light_color = Color(0xFFBC0F2E)
val light_oncolor = Color(0xFFFFFFFF)
val light_colorContainer = Color(0xFFFFDAD9)
val light_oncolorContainer = Color(0xFF410008)
val dark_color = Color(0xFFFFB3B2)
val dark_oncolor = Color(0xFF680013)
val dark_colorContainer = Color(0xFF92001F)
val dark_oncolorContainer = Color(0xFFFFDAD9)